### ISSUE TITLE
arduino1.6.5 编译失败

### ISSUE THREAD

**Issue by lfp136** [kilroy42/STFT#1]
请帮忙确认一下,下载编译失败:

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:28:0,
                 from Benchmark.ino:1:
font1.h:6: error: variable 'fontArlrdbd12Offsets' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 uint16_t fontArlrdbd12Offsets[] PROGMEM = { 0, 15, 31, 106, 169, 262, 331, 339, 372, 405, 440, 504, 513, 524, 530, 566, 623, 674, 725, 776, 839, 890, 947, 998, 1055, 1112, 1127, 1145, 1203, 1239, 1297, 1342, 1450, 1519, 1576, 1645, 1714, 1771, 1822, 1897, 1960, 1981, 2014, 2077, 2128, 2203, 2266, 2341, 2398, 2485, 2548, 2605, 2668, 2731, 2800, 2899, 2968, 3031, 3100, 3133, 3169, 3202, 3233, 3240, 3251, 3295, 3352, 3391, 3448, 3492, 3531, 3588, 3639, 3654, 3680, 3731, 3746, 3812, 3851, 3895, 3952, 4009, 4042, 4081, 4120, 4159, 4203, 4265, 4309, 4366, 4405, 4464, 4483, 4542, 4567, 4624, 4681, 4732, 4818, 4911, 4989, 5046 }; // last value = size of font data
                                 ^
font1.h:7: error: variable 'fontArlrdbd12Data' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 uint8_t  fontArlrdbd12Data[]    PROGMEM = {
                                 ^
numbers1.h:6: error: variable 'fontArlrdbd56Offsets' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 uint16_t fontArlrdbd56Offsets[] PROGMEM = { 0, 535, 844, 1234, 1684, 2114, 2517, 3056, 3370, 3955, 4499, 4573 }; // last value = size of font data
                                 ^
numbers1.h:7: error: variable 'fontArlrdbd56Data' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 uint8_t  fontArlrdbd56Data[]    PROGMEM = {
                                 ^
variable 'fontArlrdbd12Offsets' must be const in order to be put into read-only section by means of '**attribute**((progmem))'

**Comment by kilroy42** [comment]
Issue is resolved in current commit, please update
